config/routes.rb
Rails.application.routes.draw do



  get 'votes/create' => 'votes#create' #  will not need to load a page

  get 'pages/index'
  get 'pages/show'
  get 'pages/profile' 
  get 'pages/myprofile'
  
  root to: "compares#index"
  
  resources :compares

  
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #tell Devise in which controller we will implement Omniauth callbacks:

  


  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compare.rb
class Compare < ApplicationRecord
  belongs_to :user
  #paperclip setup
  has_attached_file :compareimg1, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :compareimg1, content_type: /\Aimage\/.*\z/
  # validates_attachment_file_name :compareimg1, :matches => [/png\Z/, /jpe?g\Z/]

  has_attached_file :compareimg2, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :compareimg2, content_type: /\Aimage\/.*\z/
  # validates_attachment_file_name :compareimg2, :matches => [/png\Z/, /jpe?g\Z/]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]       
  validates_presence_of :username
  has_many :compares
  #paperclip setup
  has_attached_file :avatar, style: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  
  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates_uniqueness_of :user_id, :scope => :compare_id
  
  belongs_to :user
  belongs_to :compare

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    end
end

app/controllers/compares_controller.rb
class ComparesController < ApplicationController
  
  
  def index
    # if user_signed_in?
      @compares = Compare.all
    #   render 'index'
    # else
    #   redirect_to new_user_session_path
    # end
      # @voted = Vote.where user_id: current_user.id;
      @user = User.find(current_user.id)
  end
  def show
    @compare = Compare.find(params[:id])
   
    
  end
  
  def new
    @compare = Compare.new
  end
  
  def create

    @compare = Compare.new(compare_parameters)
    
    @compare.user_id = current_user.id
    @compare.save
  
    if @compare.save
    redirect_to compare_path(@compare)
    else
      render 'new'
    end
  end
  
  def edit
    @compare = Compare.find(params[:id])
  end
  def update
    
    @compare = Compare.find(params[:id])
    if @compare.update(compare_parameters)
      redirect_to @compare
    else
      render 'edit'
    end
  end
  
  def destroy
    @compare = Compare.find(params[:id])
    @compare.destroy
    redirect_to compares_path
  end
  
  private
  def compare_parameters
    params.require(:compare).permit(:headline, :compareimg1, :compareimg2)
  end
  
  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def index
    if user_signed_in?
      @compares = Compare.all
    else
      @compares = Compare.find(:all, :order => "id desc", :limit => 5)
    end
  end

  def profile
      
       @user = User.find(params[:format])
       @compares = @user.compares
      # @compare = Compare.find(params[:format])
      # @user = @compare.user.username
  end
  
  def myprofile
      @compares = Compare.all.where(user:current_user.id)
      @user = current_user
  end

  def show
    @compare = Compare.find_by(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    
    def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    if @user.persisted?
      
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      
    else
      
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  def create
    
 if user_signed_in? 
    @vote = Vote.new()
    @vote.user_id = current_user.id
    @vote.compare_id = params[:compare_id].to_i
    @vote.choice = params[:choice]
    @compare = Compare.find(params[:compare_id])
    
    if !@vote.save #offloaded the work of checking to ACTIVE RECORD if save fail its not unique.
      redirect_to root_path, :flash => {:error => "You cannot vote twice, Lets keep it fair."}
    else 
      if params[:choice] === "this"
       
        @compare.img1_pts += 1
        @compare.save
        redirect_to root_path
        
      else
        @compare.img2_pts += 1
        @compare.save
        redirect_to root_path
      end
     end
   else
redirect_to  new_user_session_path
 end
end
  
end



 
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compares_helper.rb
module ComparesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/compares/_compare.html.erb
    
    <div class="card yellow lighten-5 z-depth-4">
            <div class="card-content white-text">
              <span class="card-title center"><h3><%= link_to @compare.headline, compare_path(@compare), :class => " cyan-text"  %></h3></span>
              <%= image_tag @compare.user.avatar.url %>
    <div class="compare">
      <div class="comp">
        <img  src='<%= @compare.img1_url%>'><br>
            <%= link_to "this", votes_create_path(:choice => "this", :compare_id => @compare.id.to_i), :class =>"waves-effect waves-light btn cyan accent-4" %>
            <h4 class="center-align cyan-text"><%= @compare.img1_pts %></h4>
      </div>
      <div class="comp">
        <img src='<%= @compare.img2_url%>'><br>
            <%= link_to "that", votes_create_path(:choice => "that", :compare_id => @compare.id.to_i), :class =>"waves-effect waves-light btn cyan accent-4" %>
             <h4 class="center-align cyan-text"><%= @compare.img2_pts %></h4>
      </div>
    </div> 
       <% if user_signed_in? %>
            <div class="comparesContainer flexSpaceBetween">
                <% if @compare.user_id === current_user.id %>
                    <%= link_to "Edit this Comparative", edit_compare_path(@compare) %>
                    <%= link_to "Delete this Comparative", compare_path(@compare), method: :delete, data: {confirm: "Are you sure?"}%>
                <% end %>
                
        <% end %>
        </div>
       </div>
           
          </div>

app/views/compares/_compares.html.erb
 <% @compares.each do |x|%>
  
      <div class="card yellow lighten-5 z-depth-4" id="boob">
        <div class="card-content white-text">
          <span class="card-title center-align "><h3><%= link_to x.headline, compare_path(x), :class => " cyan-text"  %></h3><h6><%= link_to "by " + x.user.username, pages_profile_path(x.user_id)%> </h6></span>              
          <div class="compare">
            <div class="comp">
              <img  src='<%= x.img1_url%>'><br>
              <%= link_to "this", votes_create_path(:choice => "this", :compare_id => x.id.to_i), :class =>"waves-effect waves-light btn cyan accent-4" %>
              <h4 class="center-align cyan-text"><%= x.img1_pts %></h4>
            </div>
            <div class="comp">
              <img src='<%= x.img2_url%>'><br>
              <%= link_to "that", votes_create_path(:choice => "that", :compare_id => x.id.to_i), :class =>"waves-effect waves-light btn cyan accent-4" %>
              <h4 class="center-align cyan-text"><%= x.img2_pts %></h4>
            </div>
          </div> 
      </div>
    </div>
    

   
    <!--</div>-->
    <!--</div>-->
  <%end%>
 
 

              
         

app/views/compares/_new.html.erb
  <div class="row  center-align">
   <div class="col s12 m4 offset-m4">
    <div class="card yellow lighten-5 z-depth-4">
      <div class="card-content black-text devise">
        <span class="card-title"><h3 class="devise">New Comparative</h3></span>
        <%= form_for @compare do |f| %>

        <%= f.label :headline%>
        <%= f.text_field :headline%>

        <%= f.label :compareimg1%>
        <%= f.file_field :compareimg1 %>
        <br>
        <%= f.label :compareimg2%>
        <%= f.file_field :compareimg2 %>

        <%= f.submit :class =>"waves-effect waves-light btn cyan accent-4"%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/compares/_no_compares.html.erb
    <div class="card yellow lighten-5 z-depth-4">
            <div class="card-content ">
              <span class="card-title center"><h3 class = "cyan-text"> DERP! </h3></span>
                <div class="comparesContainer flexCenter">
                   <h6 class="center-align cyan-text">Look like you have no compararives. You can create one by using the button below ...</h6><br>
                   <%= link_to "New Comparative", new_compare_path,  :class =>"waves-effect waves-light btn center cyan"%>
                </div> 
   
            </div>
      </div>
           

app/views/compares/_user_compares.html.erb
 <% @compares.each do |x|%>
  
  <div class="card yellow lighten-5 z-depth-4">
            <div class="card-content white-text">
              <span class="card-title "><h3 class="center align"><%= link_to x.headline, compare_path(x), :class => " cyan-text"  %></h3></span>
    <div class="compare">
      <div class="comp">
        <img  src='<%= x.img1_url%>'><br>
            <%= link_to "this", votes_create_path(:choice => "this", :compare_id => x.id.to_i), :class =>"waves-effect waves-light btn cyan accent-4" %>
            <h4 class="center-align cyan-text"><%= x.img1_pts %></h4>
      </div>
      <div class="comp">
        <img src='<%= x.img2_url%>'><br>
            <%= link_to "that", votes_create_path(:choice => "that", :compare_id => x.id.to_i), :class =>"waves-effect waves-light btn cyan accent-4" %>
            <h4 class="center-align cyan-text"><%= x.img2_pts %></h4>
      </div>
    </div> 
    </div>
    </div>
  <%end%>
 
 

              
         

app/views/compares/edit.html.erb
<%= render 'new'%>

app/views/compares/index.html.erb
<div class="cyan lighten-5">
<h1 class= "center-align headerMsg ">Whats happening?</h1></br>
</div>



<div class="comparesContainer">
<%=render 'compares'%>
</div>



 

app/views/compares/new.html.erb
<%= render 'new' %>

app/views/compares/show.html.erb
<div class="comparesContainer devise">
<%=render 'compare'%>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer  cyan darken-1">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Want to Help?</h5>
                <p class="grey-text text-lighten-4">You can help me get a good grade by using this app. Compare any two photo you like and get a crowd sourced analyses to help you choose your best self tp present!</p>
                
                <%if user_signed_in?%>
                <%= link_to "Start Now", new_compare_path,  :class =>" black-text yellow waves-effect waves-light btn"%>
                <%else %>
                <%= link_to "Start Now", new_user_registration_path,  :class =>" black-text yellow waves-effect waves-light btn"%>
                <%end%>
              </div>
              <div class="col l4 offset-l2 s12">
                 <h5 class="white-text center-align">Connect with the creator</h5><br>
                <div class= "comparesContainer devise">
               
                
               <a class="grey-text text-lighten-3" href="https://www.facebook.com/rafael.fernandez.161009"><i class="fa fa-facebook fa-3x" aria-hidden="true"></i></a>
                 <a class="grey-text text-lighten-3" href="https://github.com/myztajay"><i class="fa fa-github fa-3x" aria-hidden="true"></i></a>
                  <a class="grey-text text-lighten-3" href="https://www.linkedin.com/in/rafael-fernandez"><i class="fa fa-linkedin fa-3x" aria-hidden="true"></i></a>
                  <a class="grey-text text-lighten-3" href="https://twitter.com/Reactor_7"><i class="fa fa-twitter fa-3x" aria-hidden="true"></i></a>
                </div>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 Comparative
          
            </div>
          </div>

        </footer>

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
  <%=render 'layouts/nav_user'%>
<%else%>
  <%=render 'layouts/nav_guest' %>
<%end%>

app/views/layouts/_nav_guest.html.erb
  <div class = "navbar-fixed">
<!--Regualar nav-->
<nav class="cyan">
  <div class="nav-wrapper cyan container">
   <img class="logo" src="/logo.png"></img> <a href="#" class="brand-logo">Comparative</a>
    
     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Explore", compares_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
      <li class='active'><%= link_to "Sign up", new_user_registration_path %></li>
    </ul>
    
    
    <!--mobile collapse-->
        <ul class="side-nav" id="mobile-demo">
      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "My Comparative", pages_profile_path %></li>
      <!-- Dropdown Trigger -->
      <li><%= link_to "New Comparative", new_user_registration_path,  :class =>"waves-effect waves-light btn"%></li>
    </ul>
  </div>
  
  
</nav>
  </div>

app/views/layouts/_nav_user.html.erb
  <div class = "navbar-fixed">
 
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "blank", pages_profile_path %></li>
  <li><%= link_to "Settings",  edit_user_registration_path %></li>
  <li class="divider"></li>
  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
</ul>

<!--Regualar nav-->
<nav class="cyan">
  <div class="nav-wrapper cyan container">
    <img class="logo" src="/logo.png"></img> <a class="brand-logo">Comparative</a>
     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "My Comparative", pages_myprofile_path %></li>
      <li><%= link_to "Settings", edit_user_registration_path %></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%=current_user.username%></a></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "New Comparative", new_compare_path,  :class =>" black-text yellow waves-effect waves-light btn"%></li>
    </ul>
    
    
    <!--mobile collapse-->
        <ul class="side-nav" id="mobile-demo">
      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "My Comparative", pages_profile_path %></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%=current_user.username%></a></li>
       
      <li><%= link_to "New Comparative", new_compare_path,  :class =>"waves-effect waves-light btn"%></li>
    </ul>
  </div>
  
  
</nav>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Comparative</title>
    <%= csrf_meta_tags %>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>
 <%= render 'layouts/nav' %>

    <body class = "cyan lighten-5" >
        <div class="wrapper">
          <% if notice %>
           <p class="alert alert-success"></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>', 4000)
          <% end %>
          <!--renders templates-->
          <%= yield %>
        </div>
        
   <script>$(document).ready(function(){
      $('.parallax').parallax();
    
    });</script> 
        
    </body>
    
    <%= render 'layouts/footer'%>
    
</html>

app/views/pages/_compares.html.erb
 <% @compares.each do |x|%>
  
  <div class="row">
   <div class="col s12 m6 offset-m3">
    <div class="card yellow lighten-5 z-depth-4">
            <div class="card-content white-text">
              <span class="card-title"><h3><%= link_to x.headline, compare_path(x), :class => " cyan-text"  %></h3></span>
              
    <div class="compare">
      <div class="comp1">
        <img  src='<%= x.img1_url%>'><br>
        
<a class="waves-effect waves-light btn cyan accent-4">this</a>
      </div>
      <div class="comp2">
        <img src='<%= x.img2_url%>'><br>
        
<a class="waves-effect waves-light btn cyan accent-4">that</a>
      </div>
    </div> 
    
    
       </div>
           
          </div>
    </div>
    </div>
  <%end%>
 
 

              
         

app/views/pages/index.html.erb
  
  <div class="camera"><div class="overlay"> <h1> A new way to find your best self
  </h1><br><%= link_to "Start Now", new_user_registration_path,  :class =>" black-text yellow waves-effect waves-light btn"%></div></div></div>
  </div>
  

app/views/pages/myprofile.html.erb
<h1 class="center-align"><%=@user.username%>'s  Comparatives</h1>
<div class="comparesContainer flexCenter">
    <%if @user.compares.length == 0 %>
        <%= render '/compares/no_compares' %>
    <%else%>
        <%= render '/compares/user_compares' %>
    <% end %>
</div>

app/views/pages/profile.html.erb
<h1 class="center-align">Your Comparatives</h1>
<div class="comparesContainer flexCenter">
<%= render '/compares/user_compares' %>

</div>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>